-- Setup script for Asana Task Analysis table in Snowflake
-- This table stores AI-analyzed Asana tasks for dashboard display

-- Drop existing table if you need to recreate (CAREFUL - this deletes data!)
-- DROP TABLE IF EXISTS SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS;

-- Create table with new schema
CREATE TABLE IF NOT EXISTS SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS (
    TASK_GID VARCHAR(50) PRIMARY KEY,
    TASK_NAME VARCHAR(500) NOT NULL,
    PROJECT VARCHAR(200),
    ASSIGNEE_NAME VARCHAR(200),
    ASSIGNEE_GID VARCHAR(50),
    DUE_DATE DATE,
    CATEGORY VARCHAR(50),
    SECTION VARCHAR(200),
    COMPLETED BOOLEAN DEFAULT FALSE,
    AI_SUMMARY VARCHAR(5000),
    DRAFT_COMMENT VARCHAR(5000),
    ACTION_PLAN VARCHAR(5000),
    PRIORITY_ASSESSMENT VARCHAR(1000),
    BLOCKERS VARCHAR(5000),
    SUBTASKS_JSON VARCHAR(10000),
    COMMENTS_JSON VARCHAR(10000),
    ATTACHMENTS_JSON VARCHAR(10000),
    PERMALINK_URL VARCHAR(500),
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- If table exists but missing columns, add them:
-- ALTER TABLE SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS ADD COLUMN PROJECT VARCHAR(200);
-- ALTER TABLE SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS ADD COLUMN ASSIGNEE_GID VARCHAR(50);
-- ALTER TABLE SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS ADD COLUMN SUBTASKS_JSON VARCHAR(10000);
-- ALTER TABLE SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS ADD COLUMN COMMENTS_JSON VARCHAR(10000);
-- ALTER TABLE SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS ADD COLUMN ATTACHMENTS_JSON VARCHAR(10000);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS IDX_CATEGORY ON SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS(CATEGORY);
CREATE INDEX IF NOT EXISTS IDX_DUE_DATE ON SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS(DUE_DATE);
CREATE INDEX IF NOT EXISTS IDX_COMPLETED ON SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS(COMPLETED);

-- Verify table structure
DESC TABLE SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS;

-- Test query
SELECT
    CATEGORY,
    COUNT(*) AS TASK_COUNT
FROM SOVEREIGN_MIND.RAW.ASANA_TASK_ANALYSIS
WHERE COMPLETED = FALSE
GROUP BY CATEGORY
ORDER BY TASK_COUNT DESC;
